//! Functional identifiers extracted from ck3-mod-base 58aec95f6 / 3b2b243d9 / 0ec13350c.
//! Ordered obligation and level identities only; no runtime dependency on that checkout.
pub(super) struct Group {
    pub name: &'static str,
    pub old: &'static [&'static [&'static str]],
    pub target: &'static [&'static str],
}
pub(super) struct Obligation {
    pub name: &'static str,
    pub old: &'static [&'static str],
    pub target: &'static [&'static str],
    pub default: usize,
}
pub(super) const GROUPS: &[Group] = &[
    Group {
        name: "feudal_vassal",
        old: &[&[
            "feudal_government_taxes",
            "feudal_government_levies",
            "special_contract",
            "religious_rights",
            "fortification_rights",
            "coinage_rights",
            "succession_rights",
            "war_declaration_rights",
            "council_rights",
            "title_revocation_rights",
            "jizya_special_rights",
        ]],
        target: &[
            "feudal_government_taxes",
            "feudal_government_levies",
            "special_contract",
            "religious_rights",
            "fortification_rights",
            "coinage_rights",
            "succession_rights",
            "war_declaration_rights",
            "council_rights",
            "kurultai_rights",
            "title_revocation_rights",
            "jizya_special_rights",
        ],
    },
    Group {
        name: "republic_vassal",
        old: &[&["republic_government_obligations"]],
        target: &["republic_government_obligations"],
    },
    Group {
        name: "theocracy_vassal",
        old: &[&["theocracy_government_obligations"]],
        target: &["theocracy_government_obligations"],
    },
    Group {
        name: "clan_vassal",
        old: &[&[
            "clan_tax_collector_obligations",
            "special_contract",
            "religious_rights",
            "war_declaration_rights",
            "council_rights",
            "title_revocation_rights",
            "marriage_favor_rights",
        ]],
        target: &[
            "clan_tax_collector_obligations",
            "special_contract",
            "religious_rights",
            "war_declaration_rights",
            "council_rights",
            "kurultai_rights",
            "title_revocation_rights",
            "marriage_favor_rights",
        ],
    },
    Group {
        name: "tribal_vassal",
        old: &[&["tribal_government_obligations"]],
        target: &["tribal_government_obligations"],
    },
    Group {
        name: "admin_vassal",
        old: &[
            &["administrative_obligations", "administrative_themes"],
            &[
                "administrative_obligations",
                "administrative_themes",
                "administrative_salary_rank",
            ],
        ],
        target: &[
            "administrative_obligations",
            "administrative_themes",
            "administrative_salary_rank",
        ],
    },
    Group {
        name: "nomad_vassal",
        old: &[&[
            "nomad_government_herd",
            "nomad_government_taxes",
            "liege_war_participation_obligation",
            "kurultai_rights",
            "war_declaration_rights",
        ]],
        target: &[
            "nomad_government_herd",
            "nomad_government_taxes",
            "liege_war_participation_obligation",
            "council_rights",
            "kurultai_rights",
            "war_declaration_rights",
        ],
    },
    Group {
        name: "tributary_settled",
        old: &[&[
            "default_tributary_taxes",
            "default_tributary_levies",
            "default_tributary_prestige",
            "suzerain_war_participation_guarantee",
            "tributary_war_participation_obligation",
        ]],
        target: &[
            "default_tributary_taxes",
            "default_tributary_levies",
            "default_tributary_prestige",
            "suzerain_war_participation_guarantee",
            "tributary_war_participation_obligation",
        ],
    },
    Group {
        name: "tributary_nomadic",
        old: &[&[
            "nomad_government_herd",
            "nomad_government_prestige",
            "suzerain_war_participation_guarantee",
            "tributary_war_participation_obligation",
        ]],
        target: &[
            "nomad_government_herd",
            "nomad_government_prestige",
            "suzerain_war_participation_guarantee",
            "tributary_war_participation_obligation",
        ],
    },
    Group {
        name: "tributary_subjugated",
        old: &[&[
            "default_tributary_taxes",
            "default_tributary_prestige",
            "suzerain_war_participation_guarantee",
            "tributary_war_participation_obligation",
        ]],
        target: &[
            "default_tributary_taxes",
            "default_tributary_prestige",
            "suzerain_war_participation_guarantee",
            "tributary_war_participation_obligation",
        ],
    },
    Group {
        name: "tributary_steppe",
        old: &[&[
            "default_tributary_taxes",
            "nomad_government_prestige",
            "suzerain_war_participation_guarantee",
            "tributary_war_participation_obligation",
        ]],
        target: &[
            "default_tributary_taxes",
            "nomad_government_prestige",
            "suzerain_war_participation_guarantee",
            "tributary_war_participation_obligation",
        ],
    },
    Group {
        name: "herder_vassal",
        old: &[&["herder_government_obligations"]],
        target: &["herder_government_obligations"],
    },
    Group {
        name: "celestial_vassal",
        old: &[&[
            "celestial_obligations",
            "celestial_ministry_obligations",
            "celestial_provinces",
            "celestial_treasury",
            "celestial_salary",
            "celestial_ministry_budget",
            "celestial_salary_rank",
        ]],
        target: &[
            "celestial_obligations",
            "celestial_ministry_obligations",
            "celestial_provinces",
            "celestial_treasury",
            "celestial_salary",
            "celestial_ministry_budget",
            "celestial_salary_rank",
        ],
    },
    Group {
        name: "tributary_celestial",
        old: &[&[
            "celestial_tribute_gold",
            "celestial_tribute_prestige",
            "celestial_tributary_investiture_privilege_trade",
            "celestial_tributary_investiture_privilege_marriage",
            "celestial_tributary_investiture_privilege_politics",
        ]],
        target: &[
            "celestial_tribute_gold",
            "celestial_tribute_prestige",
            "celestial_tributary_investiture_privilege_trade",
            "celestial_tributary_investiture_privilege_marriage",
            "celestial_tributary_investiture_privilege_politics",
        ],
    },
    Group {
        name: "tributary_hegemonic",
        old: &[&["hegemonic_tribute_gold", "hegemonic_tribute_prestige"]],
        target: &["hegemonic_tribute_gold", "hegemonic_tribute_prestige"],
    },
    Group {
        name: "mandala_vassal",
        old: &[&[
            "mandala_government_taxes",
            "mandala_government_piety",
            "mandala_government_levies",
            "religious_rights",
            "fortification_rights",
            "coinage_rights",
            "succession_rights",
            "title_revocation_rights",
        ]],
        target: &[
            "mandala_government_taxes",
            "mandala_government_piety",
            "mandala_government_levies",
            "religious_rights",
            "fortification_rights",
            "coinage_rights",
            "succession_rights",
            "title_revocation_rights",
        ],
    },
    Group {
        name: "tributary_mandala",
        old: &[&[
            "mandala_government_taxes",
            "mandala_government_piety",
            "mandala_government_levies",
            "mandala_suzerain_war_participation_guarantee",
        ]],
        target: &[
            "mandala_government_taxes",
            "mandala_government_piety",
            "mandala_government_levies",
            "mandala_suzerain_war_participation_guarantee",
        ],
    },
    Group {
        name: "tributary_mandala_tribal",
        old: &[&[
            "mandala_government_taxes",
            "mandala_government_prestige",
            "mandala_government_piety",
            "mandala_government_levies",
            "mandala_suzerain_war_participation_guarantee",
        ]],
        target: &[
            "mandala_government_taxes",
            "mandala_government_prestige",
            "mandala_government_piety",
            "mandala_government_levies",
            "mandala_suzerain_war_participation_guarantee",
        ],
    },
    Group {
        name: "japan_administrative_vassal",
        old: &[&[
            "japan_administrative_obligations",
            "japan_administrative_provinces",
        ]],
        target: &[
            "japan_administrative_obligations",
            "japan_administrative_provinces",
        ],
    },
    Group {
        name: "japan_feudal_vassal",
        old: &[&[
            "feudal_government_taxes",
            "feudal_government_levies",
            "special_contract",
            "religious_rights",
            "fortification_rights",
            "coinage_rights",
            "succession_rights",
            "war_declaration_rights",
            "council_rights",
            "title_revocation_rights",
            "jizya_special_rights",
        ]],
        target: &[
            "feudal_government_taxes",
            "feudal_government_levies",
            "special_contract",
            "religious_rights",
            "fortification_rights",
            "coinage_rights",
            "succession_rights",
            "war_declaration_rights",
            "council_rights",
            "kurultai_rights",
            "title_revocation_rights",
            "jizya_special_rights",
        ],
    },
    Group {
        name: "wanua_vassal",
        old: &[&["wanua_obligations"]],
        target: &["wanua_obligations"],
    },
    Group {
        name: "tributary_wanua",
        old: &[&[
            "default_tributary_taxes",
            "default_tributary_prestige",
            "barter_goods_obligations",
        ]],
        target: &[
            "default_tributary_taxes",
            "default_tributary_prestige",
            "barter_goods_obligations",
        ],
    },
    Group {
        name: "meritocratic_vassal",
        old: &[&[
            "meritocratic_obligations",
            "meritocratic_provinces",
            "meritocratic_treasury",
            "meritocratic_salary",
            "meritocratic_salary_rank",
        ]],
        target: &[
            "meritocratic_obligations",
            "meritocratic_provinces",
            "meritocratic_treasury",
            "meritocratic_salary",
            "meritocratic_salary_rank",
        ],
    },
];
pub(super) const OBLIGATIONS: &[Obligation] = &[
    Obligation {
        name: "administrative_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "administrative_salary_rank",
        old: &[
            "administrative_salary_rank_none",
            "administrative_salary_rank_duchy",
            "administrative_salary_rank_kingdom",
            "administrative_salary_rank_empire",
        ],
        target: &[
            "administrative_salary_rank_none",
            "administrative_salary_rank_duchy",
            "administrative_salary_rank_kingdom",
            "administrative_salary_rank_empire",
        ],
        default: 0,
    },
    Obligation {
        name: "administrative_themes",
        old: &[
            "admin_theme_balanced",
            "admin_theme_civilian",
            "admin_theme_military",
            "admin_theme_frontier",
            "admin_theme_imperial",
            "admin_theme_naval",
        ],
        target: &[
            "admin_theme_balanced",
            "admin_theme_civilian",
            "admin_theme_military",
            "admin_theme_frontier",
            "admin_theme_imperial",
            "admin_theme_naval",
        ],
        default: 0,
    },
    Obligation {
        name: "barter_goods_obligations",
        old: &[
            "barter_goods_low",
            "barter_goods_medium",
            "barter_goods_high",
        ],
        target: &[
            "barter_goods_low",
            "barter_goods_medium",
            "barter_goods_high",
        ],
        default: 1,
    },
    Obligation {
        name: "celestial_ministry_budget",
        old: &[
            "celestial_ministry_budget_low",
            "celestial_ministry_budget_medium",
            "celestial_ministry_budget_high",
        ],
        target: &[
            "celestial_ministry_budget_low",
            "celestial_ministry_budget_medium",
            "celestial_ministry_budget_high",
        ],
        default: 1,
    },
    Obligation {
        name: "celestial_ministry_obligations",
        old: &[
            "celestial_minister_none",
            "celestial_minister_civil",
            "celestial_minister_military",
        ],
        target: &[
            "celestial_minister_none",
            "celestial_minister_civil",
            "celestial_minister_military",
        ],
        default: 0,
    },
    Obligation {
        name: "celestial_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "celestial_provinces",
        old: &[
            "celestial_province_standard",
            "celestial_province_industrial",
            "celestial_province_metropolitan",
            "celestial_province_military",
            "celestial_province_protectorate",
        ],
        target: &[
            "celestial_province_standard",
            "celestial_province_industrial",
            "celestial_province_metropolitan",
            "celestial_province_military",
            "celestial_province_protectorate",
        ],
        default: 0,
    },
    Obligation {
        name: "celestial_salary",
        old: &[
            "celestial_salary_very_low",
            "celestial_salary_low",
            "celestial_salary_medium",
            "celestial_salary_high",
            "celestial_salary_very_high",
        ],
        target: &[
            "celestial_salary_very_low",
            "celestial_salary_low",
            "celestial_salary_medium",
            "celestial_salary_high",
            "celestial_salary_very_high",
        ],
        default: 2,
    },
    Obligation {
        name: "celestial_salary_rank",
        old: &[
            "celestial_salary_rank_none",
            "celestial_salary_rank_county",
            "celestial_salary_rank_duchy",
            "celestial_salary_rank_kingdom",
            "celestial_salary_rank_empire",
            "celestial_salary_rank_minister",
        ],
        target: &[
            "celestial_salary_rank_none",
            "celestial_salary_rank_county",
            "celestial_salary_rank_duchy",
            "celestial_salary_rank_kingdom",
            "celestial_salary_rank_empire",
            "celestial_salary_rank_minister",
        ],
        default: 0,
    },
    Obligation {
        name: "celestial_treasury",
        old: &[
            "celestial_treasury_very_low",
            "celestial_treasury_low",
            "celestial_treasury_medium",
            "celestial_treasury_high",
            "celestial_treasury_very_high",
        ],
        target: &[
            "celestial_treasury_very_low",
            "celestial_treasury_low",
            "celestial_treasury_medium",
            "celestial_treasury_high",
            "celestial_treasury_very_high",
        ],
        default: 2,
    },
    Obligation {
        name: "celestial_tributary_investiture_privilege_marriage",
        old: &["investiture_marriage_no", "investiture_marriage_yes"],
        target: &["investiture_marriage_no", "investiture_marriage_yes"],
        default: 0,
    },
    Obligation {
        name: "celestial_tributary_investiture_privilege_politics",
        old: &["investiture_politics_no", "investiture_politics_yes"],
        target: &["investiture_politics_no", "investiture_politics_yes"],
        default: 0,
    },
    Obligation {
        name: "celestial_tributary_investiture_privilege_trade",
        old: &["investiture_trade_no", "investiture_trade_yes"],
        target: &["investiture_trade_no", "investiture_trade_yes"],
        default: 0,
    },
    Obligation {
        name: "celestial_tribute_gold",
        old: &[
            "celestial_tributary_tax_none",
            "celestial_tributary_tax_low",
            "celestial_tributary_tax_normal",
            "celestial_tributary_tax_high",
        ],
        target: &[
            "celestial_tributary_tax_none",
            "celestial_tributary_tax_low",
            "celestial_tributary_tax_normal",
            "celestial_tributary_tax_high",
        ],
        default: 1,
    },
    Obligation {
        name: "celestial_tribute_prestige",
        old: &[
            "celestial_prestige_transfer_none",
            "celestial_prestige_transfer_low",
            "celestial_prestige_transfer_normal",
            "celestial_prestige_transfer_high",
        ],
        target: &[
            "celestial_prestige_transfer_none",
            "celestial_prestige_transfer_low",
            "celestial_prestige_transfer_normal",
            "celestial_prestige_transfer_high",
        ],
        default: 2,
    },
    Obligation {
        name: "clan_tax_collector_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "coinage_rights",
        old: &["coinage_rights_none", "coinage_rights_granted"],
        target: &["coinage_rights_none", "coinage_rights_granted"],
        default: 0,
    },
    Obligation {
        name: "council_rights",
        old: &["council_rights_none", "council_rights_guaranteed"],
        target: &["council_rights_none", "council_rights_guaranteed"],
        default: 0,
    },
    Obligation {
        name: "default_tributary_levies",
        old: &[
            "tributary_levies_exempt",
            "tributary_levies_low",
            "tributary_levies_high",
        ],
        target: &[
            "tributary_levies_exempt",
            "tributary_levies_low",
            "tributary_levies_high",
        ],
        default: 1,
    },
    Obligation {
        name: "default_tributary_prestige",
        old: &[
            "prestige_transfer_none",
            "prestige_transfer_normal",
            "prestige_transfer_high",
        ],
        target: &[
            "prestige_transfer_none",
            "prestige_transfer_normal",
            "prestige_transfer_high",
        ],
        default: 1,
    },
    Obligation {
        name: "default_tributary_taxes",
        old: &[
            "tributary_tax_none",
            "tributary_tax_low",
            "tributary_tax_high",
        ],
        target: &[
            "tributary_tax_none",
            "tributary_tax_low",
            "tributary_tax_high",
        ],
        default: 2,
    },
    Obligation {
        name: "feudal_government_levies",
        old: &[
            "feudal_levies_exempt",
            "feudal_levies_low",
            "feudal_levies_normal",
            "feudal_levies_high",
            "feudal_levies_extortionate",
        ],
        target: &[
            "feudal_levies_exempt",
            "feudal_levies_low",
            "feudal_levies_normal",
            "feudal_levies_high",
            "feudal_levies_extortionate",
        ],
        default: 2,
    },
    Obligation {
        name: "feudal_government_taxes",
        old: &[
            "feudal_tax_exempt",
            "feudal_tax_low",
            "feudal_tax_normal",
            "feudal_tax_high",
            "feudal_tax_extortionate",
        ],
        target: &[
            "feudal_tax_exempt",
            "feudal_tax_low",
            "feudal_tax_normal",
            "feudal_tax_high",
            "feudal_tax_extortionate",
        ],
        default: 2,
    },
    Obligation {
        name: "fortification_rights",
        old: &["fortification_rights_none", "fortification_rights_granted"],
        target: &["fortification_rights_none", "fortification_rights_granted"],
        default: 0,
    },
    Obligation {
        name: "hegemonic_tribute_gold",
        old: &[
            "hegemonic_tributary_tax_none",
            "hegemonic_tributary_tax_low",
            "hegemonic_tributary_tax_normal",
            "hegemonic_tributary_tax_high",
        ],
        target: &[
            "hegemonic_tributary_tax_none",
            "hegemonic_tributary_tax_low",
            "hegemonic_tributary_tax_normal",
            "hegemonic_tributary_tax_high",
        ],
        default: 1,
    },
    Obligation {
        name: "hegemonic_tribute_prestige",
        old: &[
            "hegemonic_prestige_transfer_none",
            "hegemonic_prestige_transfer_low",
            "hegemonic_prestige_transfer_normal",
            "hegemonic_prestige_transfer_high",
        ],
        target: &[
            "hegemonic_prestige_transfer_none",
            "hegemonic_prestige_transfer_low",
            "hegemonic_prestige_transfer_normal",
            "hegemonic_prestige_transfer_high",
        ],
        default: 2,
    },
    Obligation {
        name: "herder_government_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "japan_administrative_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "japan_administrative_provinces",
        old: &[
            "japan_administrative_province_standard",
            "japan_administrative_province_trade",
            "japan_administrative_province_military",
        ],
        target: &[
            "japan_administrative_province_standard",
            "japan_administrative_province_trade",
            "japan_administrative_province_military",
        ],
        default: 0,
    },
    Obligation {
        name: "jizya_special_rights",
        old: &[
            "jizya_special_rights_default",
            "jizya_special_rights_granted",
        ],
        target: &[
            "jizya_special_rights_default",
            "jizya_special_rights_granted",
        ],
        default: 0,
    },
    Obligation {
        name: "kurultai_rights",
        old: &["kurultai_rights_none", "kurultai_rights_guaranteed"],
        target: &["kurultai_rights_none", "kurultai_rights_guaranteed"],
        default: 0,
    },
    Obligation {
        name: "liege_war_participation_obligation",
        old: &[
            "liege_war_participation_obligation_none",
            "liege_war_participation_obligation_forced",
        ],
        target: &[
            "liege_war_participation_obligation_none",
            "liege_war_participation_obligation_forced",
        ],
        default: 0,
    },
    Obligation {
        name: "mandala_government_levies",
        old: &[
            "mandala_levies_exempt",
            "mandala_levies_low",
            "mandala_levies_medium",
            "mandala_levies_high",
            "mandala_levies_extortionate",
        ],
        target: &[
            "mandala_levies_exempt",
            "mandala_levies_low",
            "mandala_levies_medium",
            "mandala_levies_high",
            "mandala_levies_extortionate",
        ],
        default: 1,
    },
    Obligation {
        name: "mandala_government_piety",
        old: &[
            "mandala_piety_low",
            "mandala_piety_normal",
            "mandala_piety_high",
        ],
        target: &[
            "mandala_piety_low",
            "mandala_piety_normal",
            "mandala_piety_high",
        ],
        default: 1,
    },
    Obligation {
        name: "mandala_government_prestige",
        old: &[
            "mandala_prestige_low",
            "mandala_prestige_normal",
            "mandala_prestige_high",
        ],
        target: &[
            "mandala_prestige_low",
            "mandala_prestige_normal",
            "mandala_prestige_high",
        ],
        default: 1,
    },
    Obligation {
        name: "mandala_government_taxes",
        old: &[
            "mandala_tax_exempt",
            "mandala_tax_low",
            "mandala_tax_normal",
            "mandala_tax_high",
            "mandala_tax_extortionate",
        ],
        target: &[
            "mandala_tax_exempt",
            "mandala_tax_low",
            "mandala_tax_normal",
            "mandala_tax_high",
            "mandala_tax_extortionate",
        ],
        default: 2,
    },
    Obligation {
        name: "mandala_suzerain_war_participation_guarantee",
        old: &[
            "mandala_suzerain_war_participation_guarantee_none",
            "mandala_suzerain_war_participation_guarantee_available",
        ],
        target: &[
            "mandala_suzerain_war_participation_guarantee_none",
            "mandala_suzerain_war_participation_guarantee_available",
        ],
        default: 1,
    },
    Obligation {
        name: "marriage_favor_rights",
        old: &[
            "marriage_favor_rights_default",
            "marriage_favor_rights_granted",
        ],
        target: &[
            "marriage_favor_rights_default",
            "marriage_favor_rights_granted",
        ],
        default: 0,
    },
    Obligation {
        name: "meritocratic_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "meritocratic_provinces",
        old: &[
            "meritocratic_province_standard",
            "meritocratic_province_industrial",
            "meritocratic_province_military",
        ],
        target: &[
            "meritocratic_province_standard",
            "meritocratic_province_industrial",
            "meritocratic_province_military",
        ],
        default: 0,
    },
    Obligation {
        name: "meritocratic_salary",
        old: &[
            "salary_very_low",
            "salary_low",
            "salary_medium",
            "salary_high",
            "salary_very_high",
        ],
        target: &[
            "salary_very_low",
            "salary_low",
            "salary_medium",
            "salary_high",
            "salary_very_high",
        ],
        default: 2,
    },
    Obligation {
        name: "meritocratic_salary_rank",
        old: &[
            "meritocratic_salary_rank_none",
            "meritocratic_salary_rank_county",
            "meritocratic_salary_rank_duchy",
            "meritocratic_salary_rank_kingdom",
            "meritocratic_salary_rank_empire",
        ],
        target: &[
            "meritocratic_salary_rank_none",
            "meritocratic_salary_rank_county",
            "meritocratic_salary_rank_duchy",
            "meritocratic_salary_rank_kingdom",
            "meritocratic_salary_rank_empire",
        ],
        default: 0,
    },
    Obligation {
        name: "meritocratic_treasury",
        old: &[
            "treasury_very_low",
            "treasury_low",
            "treasury_medium",
            "treasury_high",
            "treasury_very_high",
        ],
        target: &[
            "treasury_very_low",
            "treasury_low",
            "treasury_medium",
            "treasury_high",
            "treasury_very_high",
        ],
        default: 2,
    },
    Obligation {
        name: "nomad_government_herd",
        old: &[
            "herd_tax_exempt",
            "herd_tax_low",
            "herd_tax_normal",
            "herd_tax_high",
            "herd_tax_extortionate",
        ],
        target: &[
            "herd_tax_exempt",
            "herd_tax_low",
            "herd_tax_normal",
            "herd_tax_high",
            "herd_tax_extortionate",
        ],
        default: 2,
    },
    Obligation {
        name: "nomad_government_prestige",
        old: &[
            "prestige_transfer_none",
            "prestige_transfer_normal",
            "prestige_transfer_high",
        ],
        target: &[
            "prestige_transfer_none",
            "prestige_transfer_normal",
            "prestige_transfer_high",
        ],
        default: 0,
    },
    Obligation {
        name: "nomad_government_taxes",
        old: &[
            "nomad_tax_exempt",
            "nomad_tax_low",
            "nomad_tax_normal",
            "nomad_tax_high",
            "nomad_tax_extortionate",
        ],
        target: &[
            "nomad_tax_exempt",
            "nomad_tax_low",
            "nomad_tax_normal",
            "nomad_tax_high",
            "nomad_tax_extortionate",
        ],
        default: 0,
    },
    Obligation {
        name: "religious_rights",
        old: &["religious_rights_none", "religious_rights_protected"],
        target: &["religious_rights_none", "religious_rights_protected"],
        default: 0,
    },
    Obligation {
        name: "republic_government_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "special_contract",
        old: &[
            "special_contract_none",
            "special_contract_scutage",
            "special_contract_march",
            "special_contract_castellan",
            "special_contract_palatinate",
        ],
        target: &[
            "special_contract_none",
            "special_contract_scutage",
            "special_contract_march",
            "special_contract_castellan",
            "special_contract_palatinate",
        ],
        default: 0,
    },
    Obligation {
        name: "succession_rights",
        old: &[
            "succession_rights_default",
            "succession_rights_forced_partition",
        ],
        target: &[
            "succession_rights_default",
            "succession_rights_forced_partition",
        ],
        default: 0,
    },
    Obligation {
        name: "suzerain_war_participation_guarantee",
        old: &[
            "suzerain_war_participation_guarantee_none",
            "suzerain_war_participation_guarantee_available",
        ],
        target: &[
            "suzerain_war_participation_guarantee_none",
            "suzerain_war_participation_guarantee_available",
        ],
        default: 0,
    },
    Obligation {
        name: "theocracy_government_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "title_revocation_rights",
        old: &[
            "title_revocation_rights_default",
            "title_revocation_rights_protected",
        ],
        target: &[
            "title_revocation_rights_default",
            "title_revocation_rights_protected",
        ],
        default: 0,
    },
    Obligation {
        name: "tribal_government_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "tributary_war_participation_obligation",
        old: &[
            "tributary_war_participation_obligation_none",
            "tributary_war_participation_obligation_forced",
        ],
        target: &[
            "tributary_war_participation_obligation_none",
            "tributary_war_participation_obligation_forced",
        ],
        default: 0,
    },
    Obligation {
        name: "wanua_obligations",
        old: &["default"],
        target: &["default"],
        default: 0,
    },
    Obligation {
        name: "war_declaration_rights",
        old: &[
            "war_declaration_rights_default",
            "war_declaration_rights_allowed",
        ],
        target: &[
            "war_declaration_rights_default",
            "war_declaration_rights_allowed",
        ],
        default: 0,
    },
];
